import Head from 'next/head';
import Link from 'next/link';
import Image from 'next/image';
import LogIn from './components/login';
import Footer from './components/footer';
import Navbar from './components/navbar';
import styles from '../styles/Home.module.css';
import utilStyles from '../styles/lib.module.css';
import { getSortedPostsData } from '../lib/posts';

export async function getStaticProps() {
  const allPostsData = getSortedPostsData();
  return {
    props: {
      allPostsData,
    },
  };
}

const name = '[chris]';
export const siteTitle = 'online booking platform | slots'

export default function Home({ allPostsData }) {
  return (
    <div className={styles.container}>
      <Head>
      <link rel="icon" href="/favicon.ico" />
        <meta
          name="description"
          content="Learn how to build a personal website using Next.js"
        />
        <meta
          property="og:image"
          content={siteTitle}
        />
        <meta name="og:title" content={siteTitle} />
        <meta name="twitter:card" content="summary_large_image" />
        <title>{siteTitle}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>

        <Navbar />

        <div className={styles.description}>
          <LogIn />
        </div>

        {/* Add this <section> tag below the existing <section> tag */}
      <section className={`${utilStyles.headingMd} ${utilStyles.padding1px}`}>
        <h2 className={utilStyles.headingLg}>Blog</h2>
        <ul className={utilStyles.list}>
          {allPostsData.map(({ id, date, title }) => (
            <li className={utilStyles.listItem} key={id}>
              {title}
              <br />
              {id}
              <br />
              {date}
            </li>
          ))}
        </ul>
      </section>

        <div className={styles.grid}>
      
        </div>
        <Footer />
      </main>

      
    </div>
  )
}
